---
# tasks file for service
- include_vars: "{{ ansible_os_family }}.yml"
- name: 
  yum: 
    name: '{{ package }}'
    state: '{{ state }}'  
  notify: Start service
  register: out
  when: ansible_os_family == 'RedHat'


- debug:
    var: out
  when: ansible_os_family == 'RedHat'


- name: 
  apt: 
    name: '{{ package }}'
    state: '{{ state }}'
  notify: Start service
  register: out
  when: ansible_os_family == 'Debian'

- debug:
    var: out
  when: ansible_os_family == 'Debian'
